<?php 
$a = 3;
$b = 7;
$c = -5;
$shift_by_one = 1;

echo "<!doctype html>";
echo " <html>";
echo " 	<head>";
echo " 		<title>Bitwise Operations</title>";
echo " 		<meta charset = 'UTF-8'>";
echo " 	</head>";
echo " 	<body>";
echo "<table>";
echo " <tr>";
echo "   <th align='left'>Operations</th>";
echo "   <th align='left'>Solution</th>";
echo " </tr>";
echo " <tr>";
		echo "<td>$a & $b (Bitwise AND)</td>";
		echo "<td>".($a & $b)."</td>";
echo " </tr>";
echo " <tr>";
		echo "<td>$a | $b (Bitwise OR)</td>";
		echo "<td>".($a | $b)."</td>";
echo " </tr>";
echo " <tr>";
		echo "<td> $a ^ $b (Bitwise XOR)</td>";
		echo "<td>".($a ^ $b)."</td>";
echo " </tr>";
echo " <tr>";
		echo "<td> ~$b (Bitwise NOT)</td>";
		echo "<td>".(~$b)."</td>";
echo " </tr>";
echo " <tr>";
		echo "<td> $c (Bitwise NOT)</td>";
		echo "<td>".(~$c)."</td>";
echo " </tr>";
echo " <tr>";
		echo "<td> $a << $shift_by_one (Bitwise Left Shift)</td>";
		echo "<td>".($a << $shift_by_one)."</td>";
echo " <tr>";
		echo "<td> $a >> $shift_by_one (Bitwise Right Shift)</td>";
		echo "<td>".($a >> $shift_by_one)."</td>";
echo " </tr>";
echo " <tr>";
		echo "<td> 2 to the power of 3 </td>";
		echo "<td> ".pow(2,3)." </td>";
echo " </tr>";
echo "</table>";
echo " 	</body>";
echo " </html>";
?>